[package]
name = "effect-engine"
version = "0.2.0-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { version = "0.29", features = ["rwh_05"]}
wgpu = "0.19"
pollster = "0.3.0"
raw-window-handle = "0.6.0"
bytemuck = { version = "1.14", features = [ "derive" ] }
anyhow = "1.0.75"
rand = "0.8.5"
rayon = "1.8.0"
glam = "0.25"
rodio = "0.17"
num = "0.4.1"

[dependencies.image]
version = "0.25"
default-features = false
features = ["png", "jpeg"]
