[package]
name = "effect-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { version = "0.29", features = ["rwh_05"]}
wgpu = "0.18"
pollster = "0.3.0"
raw-window-handle = "0.6.0"
bytemuck = { version = "1.14", features = [ "derive" ] }
anyhow = "1.0.75"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]
